const apple = require('../assets/icons/apple.png')
const artis = require('../assets/icons/artist.png')
const logo = require('../assets/icons/logo.png')
const user = require('../assets/icons/user.png')
const calendar = require('../assets/icons/calendar.png')
const google = require('../assets/icons/google.png')
const facebook = require('../assets/icons/facebook.png')
const recCheck = require('../assets/icons/recCheck.png')
const recUncheck = require('../assets/icons/recUncheck.png')
const cirChcek = require('../assets/icons/cirCheck.png')
const cirUncheck = require('../assets/icons/cirUncheck.png')
const notVisible = require('../assets/icons/notVisible.png')
const visible = require('../assets/icons/visible.png')
const ellipse = require('../assets/icons/ellipse.png')
const visitGallary = require('../assets/icons/visitGallary.png')
const drawer = require('../assets/icons/drawer.png')
const search = require('../assets/icons/search.png')
const cart = require('../assets/icons/cart.png')
const back_arrow = require('../assets/icons/back_arrow.png')
const forward_arrow = require('../assets/icons/forward_arrow.png')
const heart = require('../assets/icons/heart.png')
const full_view = require('../assets/icons/full_view.png')
const digital_home = require('../assets/icons/digital_home.png')
const digital_event = require('../assets/icons/digital_event.png')
const digital_profile = require('../assets/icons/digital_profile.png')
const digital_scan = require('../assets/icons/digital_scan.png')
const digital_back_arrow = require('../assets/icons/digital_back_arrow.png')
const remove = require('../assets/icons/remove.png')
const digital_Un_Active = require('../assets/icons/digital_Un_Active.png')
const digital_Active = require('../assets/icons/digital_Active.png')
const digital_time = require('../assets/icons/digital_time.png')
const digital_calendar = require('../assets/icons/digital_calendar.png')
const digital_remove = require('../assets/icons/digital_remove.png')
const digital_user = require('../assets/icons/digital_user.png')
const digital_term = require('../assets/icons/digital_term.png')
const digital_about = require('../assets/icons/digital_about.png')
const digital_contact = require('../assets/icons/digital_contact.png')
const digital_service = require('../assets/icons/digital_service.png')
const digital_notification = require('../assets/icons/digital_notification.png')
const digital_privacy = require('../assets/icons/digital_privacy.png')
const digital_logout = require('../assets/icons/digital_logout.png')
const unsave = require('../assets/icons/unsave.png')
const save = require('../assets/icons/save.png')
const digital_comfirm = require('../assets/icons/digital_comfirm.png')
const tradi_comfirm = require('../assets/icons/tradi_comfirm.png')
const edit = require('../assets/icons/edit.png')
const share = require('../assets/icons/share.png')
const plus = require('../assets/icons/plus.png')
const tradi_world = require('../assets/icons/tradi_world.png')
const digital_world = require('../assets/icons/digital_world.png')
const minimize = require('../assets/icons/minimize.png')
const language = require('../assets/icons/language.png')
const digital_artist = require('../assets/icons/digital_artist.png')
const no_notification = require('../assets/icons/noNotification.png')
const no_purchase = require('../assets/icons/noPurchase.png')
const no_Favourite = require('../assets/icons/noFavourite.png')
const filter_list = require('../assets/icons/filter_list.png')
const setting = require('../assets/icons/digital_setting.png')
const question = require('../assets/icons/digital_question.png')
const digital_delete = require('../assets/icons/digital_delete.png')
const digital_lock = require('../assets/icons/digital_lock.png')
const digital_phone = require('../assets/icons/digital_phone.png')
const digital_location = require('../assets/icons/digital_location.png')
const digital_heart_fill = require('../assets/icons/digital_heart_fill.png')
const tradi_heart_fill = require('../assets/icons/tradi_heart_fill.png')
const mula_logo_name = require('../assets/icons/mula_logo_name.png')
const digital_notVisible = require('../assets/icons/digital_notVisible.png')
const digital_mula_logo_name = require('../assets/icons/digital_mula_logo_name.png')
const digital_visible = require('../assets/icons/digital_visible.png')
const camera = require('../assets/icons/camera.png')
const digital_noEvent = require('../assets/icons/digital_noEvent.png')
const tradi_noEvent = require('../assets/icons/tradi_noEvent.png')
const profile = require('../assets/icons/profile.png')
const digital_upArrow = require('../assets/icons/digital_upArrow.png')
const tradi_noData = require('../assets/icons/tradi_noData.png')
const digital_noData = require('../assets/icons/digital_noData.png')
const video = require('../assets/icons/video.png')
const article = require('../assets/icons/article.png')
const play = require('../assets/icons/play.png')
const play_video = require('../assets/icons/play_video.png')
const pause_video = require('../assets/icons/pause_video.png')
const video_forward = require('../assets/icons/video_forward.png')
const video_bardward = require('../assets/icons/video_backward.png')
const maximize = require('../assets/icons/maximize.png')
const feedback = require('../assets/icons/feedback.png')
const digital_forward_arrow = require('../assets/icons/digital_forward_arrow.png')
const replay = require('../assets/icons/replay.png')
const filter = require('../assets/icons/filter.png')
const minus = require('../assets/icons/minus.png')
const shop = require('../assets/icons/shop.png')
const location = require('../assets/icons/location.png')
const radio_checked = require('../assets/icons/radio_check.png')
const radio_unchecked = require('../assets/icons/radio_uncheck.png')
const filter_fill = require('../assets/icons/filter_fill.png')
const image_upload = require('../assets/icons/image_upload.png')
const order_successful = require('../assets/icons/order_successful.png')




export default {
    apple,artis,logo,user,calendar,google,facebook,recCheck,recUncheck,cirChcek,cirUncheck
    ,notVisible,visible,ellipse,visitGallary,drawer,search,cart,back_arrow,forward_arrow,heart,
    full_view,digital_home,digital_event,digital_profile,digital_scan,digital_back_arrow,remove,
    digital_Un_Active,digital_Active,digital_time,digital_calendar,digital_remove,digital_user,
    digital_term,digital_about,digital_contact,digital_service,digital_privacy,digital_notification,
    digital_logout,unsave,save,digital_comfirm,tradi_comfirm,edit,share,plus,digital_world,tradi_world,
    minimize,language,digital_artist,no_Favourite,no_notification,no_purchase,filter_list,
    setting,question,digital_delete,digital_lock,digital_phone,digital_location,digital_heart_fill,tradi_heart_fill,mula_logo_name,
    digital_notVisible,digital_mula_logo_name,digital_visible,camera,digital_noEvent,tradi_noEvent,profile,
    digital_upArrow,tradi_noData,digital_noData,video,article,play,play_video,pause_video,
    video_bardward,video_forward,maximize,feedback,digital_forward_arrow,replay,filter,minus,shop,radio_checked,
    radio_unchecked,location,filter_fill,image_upload,order_successful
}